//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class myProduct
    {
        public int product_id { get; set; }
        public string product_name { get; set; }
        public string product_cate { get; set; }
        public Nullable<decimal> product_price { get; set; }
    }
}
