//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class newPro
    {
        public int id { get; set; }
        public string name { get; set; }
        public string category { get; set; }
        public Nullable<decimal> price { get; set; }
    }
}
